config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "foods#index"
  resources :foods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  has_one_attached :avatar
  validates :name, presence: true
  validates :avatar, content_type: ["image/png", "image/gpeg", "image/gif"]
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :foods, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[edit update destroy]

  def index
    @foods = Food.includes(:user).order(created_at: :asc)
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def edit; end

  def create
    food = current_user.foods.create!(food_params)
    if food.save
      redirect_to food, notice: "料理情報を入力しました。"
    else
      render :error_handling, status: :unprocessable_entity
    end
  end

  def update
    @food.update!(food_params)
    if @food.update!(food_params)
      redirect_to @food
    else
      render :error_handling, status: :unprocessable_entity
    end
  end

  def destroy
    @food.destroy!
    redirect_to root_path
  end

  private

  def food_params
    params.require(:food).permit(:name, :comment, :avatar)
  end

  def set_food
    @food = current_user.foods.find_by(id: params[:id])
    return if @food.present?

    redirect_to root_path, alert: "権限がありません"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_food.html.erb
<div>
  <p>【名前】<%= food.name %></p>
  <p>【内容】<%= food.comment %></p>
  <p>
    <%= link_to "詳細", food %>
    <% if current_user.id == food.user_id  %>
      <%= link_to "編集", edit_food_path(food) %>
      <%= link_to "削除", food_path(food), data: { turbo_method: :delete, turbo_confirm: "削除してもよろしいですか?"} %>
    <%end%>
  </p>
</div>
<hr>

app/views/foods/_form.html.erb
<% preview_target_class = "js__preview-target-#{SecureRandom.uuid}" %>

<%= form_with model: @food do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name, 
                      required: true,
                      autocomplete: "name",
                      placeholder: "料理名を入力してください"
  %>
  <br>
  <p></p>
  <br>
  <%= form.label :comment%>
  <%= form.text_area :comment,
                      placeholder: "料理に関するコメントを入力してください。"
  %>
  <p>
    <%= form.file_field :avatar, accept: "image/png,image/jpeg,image/gif", class: "js__preview-input", data: { preview_target: ".#{preview_target_class}" } %>
  </p>
  <p>
    <%= image_tag "", alt: "画像のプレビュー", height: 200, class: preview_target_class, hidden: true %>
  </p>
  <br>
  <%= form.submit "送信" %>
<% end %>

app/views/foods/edit.html.erb
<h1>編集</h1>
<%= render "form" %>

app/views/foods/error_handling.turbo_stream.erb
<%= turbo_stream.replace "error-message" do %>
  <%= render "layouts/error_messages", object: @food %>
<% end %>

app/views/foods/index.html.erb
<h1>投稿一覧</h1>
<%= render @foods %>

app/views/foods/new.html.erb
<h1>新規投稿</h1>
<%= render "form" %>

app/views/foods/show.html.erb
<h1>投稿詳細</h1>
<p>【メールアドレス】<%= @food.user.email %></p>
<p>【食品名】<%= @food.name %></p>
<% if @food.avatar.attached? %>
  <div><%= image_tag @food.avatar %></div>
<% end %>
<p>【コメント】<%= @food.comment %></p>
<p>【作成日時】<%=l @food.created_at %></p>
<% if current_user.id == @food.user_id %>
<p>
  <%= link_to "編集", edit_food_path(@food) %>
  <%= link_to "削除", food_path(@food), data:{ turbo_method: :delete, turbo_confirm: "削除してもよろしいですか？" } %>
</p>
<% end %>
<p><%= link_to "投稿一覧へ", foods_path %></p>

app/views/layouts/_error_messages.html.erb
<div id="error-messages">
  <% binding.pry %>
  <% if object.error.any? %>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><span style="color: :red"><%= msg %></span></li>
      <% end %>
    </ul>
  <%end%>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <p><%= msg %></p>
  <hr>
<% end %>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<%#ログイン時%>
  <%= link_to "一覧ページへ", root_path %>
  <%= link_to "新規投稿ページ", new_food_path%>
  <%= link_to "アカウント編集", edit_user_registration_path %>
  <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: "ログアウトしますか？" } %>
  <%= "【ログイン中のアドレス】#{current_user.email}" %>
<% else %>
  <%# 非ログイン時%>
  <%= link_to "新規登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
<% end%>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecommendedFoodAppVer2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <header>
        <%= render "layouts/header" %>
        <%= render "layouts/flash" %>
      </header>
    <%= yield %>
  </body>
</html>